# Generated by Django 2.1.3 on 2018-12-07 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, max_length=50, null=True)),
                ('event_game', models.CharField(blank=True, max_length=250, null=True)),
                ('event_logo', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_project.Event')),
            ],
            options={
                'db_table': 'summary',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, max_length=30, null=True)),
                ('team_logo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='TeamInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_project.Event')),
            ],
            options={
                'db_table': 'team_information',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(blank=True, max_length=100, null=True)),
                ('game', models.CharField(blank=True, max_length=30, null=True)),
                ('tournament_mode', models.CharField(blank=True, max_length=10, null=True)),
                ('tournament_type', models.CharField(blank=True, max_length=30, null=True)),
                ('number_of_teams', models.IntegerField(blank=True, null=True)),
                ('number_of_round', models.IntegerField(blank=True, null=True)),
                ('number_of_matches', models.IntegerField(blank=True, null=True)),
                ('tournament_image', models.CharField(blank=True, max_length=100, null=True)),
                ('tournament_start', models.DateTimeField(blank=True, null=True)),
                ('tournament_end', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_project.Event')),
            ],
            options={
                'db_table': 'tournament',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank='False', max_length=25, unique='True')),
                ('password', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, default='user_default', max_length=50, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sport', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='organiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_project.User'),
        ),
        migrations.AddField(
            model_name='teaminformation',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_project.User'),
        ),
        migrations.AddField(
            model_name='teaminformation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_project.Team'),
        ),
        migrations.AddField(
            model_name='teaminformation',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_project.Tournament'),
        ),
        migrations.AddField(
            model_name='summary',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_project.Tournament'),
        ),
        migrations.AddField(
            model_name='summary',
            name='winner_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_project.Team'),
        ),
        migrations.AddField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_project.User'),
        ),
    ]
